import { ArrowRight } from "lucide-react";
import { Link } from "react-router-dom";

export default function Landing() {
  return (
    <main className="nexora-home">
      <style>{`
        .nexora-home{min-height:100svh;height:auto;overflow-x:hidden;background:#f7f8fa;color:#171a21;font-family:Inter,system-ui,sans-serif;display:flex;flex-direction:column}
        .nexora-nav{min-height:76px;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(22px,6vw,88px);border-bottom:1px solid #e4e7eb;background:#f7f8fa}
        .nexora-brand{display:flex;align-items:center;gap:10px;text-decoration:none;color:#151821;font-family:Manrope,Inter,sans-serif;font-weight:800;font-size:21px;letter-spacing:-.045em}
        .nexora-mark{width:34px;height:34px;border-radius:9px;background:#5548c9;color:#fff;display:grid;place-items:center;font-size:14px;font-weight:800;box-shadow:0 5px 14px rgba(85,72,201,.18)}
        .nexora-signin{color:#20242d;text-decoration:none;font-size:14px;font-weight:700;padding:10px 2px;border-bottom:1px solid transparent}.nexora-signin:hover{color:#5548c9;border-color:#5548c9}
        .nexora-main{flex:1;min-height:calc(100svh - 124px);display:grid;grid-template-columns:minmax(0,1fr) minmax(380px,.88fr);align-items:center;gap:clamp(42px,7vw,104px);padding:clamp(28px,5vh,60px) clamp(22px,8vw,120px)}
        .nexora-copy{max-width:680px}.nexora-title{font-family:Manrope,Inter,sans-serif;font-size:clamp(50px,6.1vw,82px);line-height:1.01;letter-spacing:-.065em;margin:0;color:#11141b;font-weight:800}.nexora-title span{color:#5548c9}
        .nexora-description{font-size:clamp(16px,1.35vw,19px);line-height:1.6;color:#4f5663;max-width:510px;margin:24px 0 30px;font-weight:500}
        .nexora-button{display:inline-flex;align-items:center;justify-content:center;gap:8px;background:#5548c9;color:#fff;text-decoration:none;border-radius:9px;padding:13px 18px;font-size:14px;font-weight:750;box-shadow:0 8px 20px rgba(85,72,201,.16)}
        .nexora-preview{width:min(100%,550px);justify-self:end;background:#fff;border:1px solid #e0e3e8;border-radius:15px;box-shadow:0 24px 65px rgba(23,28,38,.10);overflow:hidden}.preview-bar{height:38px;border-bottom:1px solid #edf0f3;display:flex;align-items:center;padding:0 14px;gap:6px}.preview-bar i{width:7px;height:7px;border-radius:50%;background:#cfd4dc}
        .preview-body{display:grid;grid-template-columns:108px 1fr;min-height:330px}.preview-side{background:#fafbfc;border-right:1px solid #edf0f3;padding:18px 11px}.preview-side strong{display:block;font:800 11px Manrope,Inter,sans-serif;color:#171a21;margin:0 5px 20px}.preview-nav{height:9px;background:#e6e9ee;border-radius:4px;margin:12px 5px}.preview-nav.active{height:28px;background:#eeecff}.preview-content{padding:23px}.preview-heading{height:10px;width:135px;background:#1c2029;border-radius:5px;margin-bottom:20px}.preview-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.preview-card{height:65px;border:1px solid #edf0f3;border-radius:9px;padding:11px}.preview-card b{display:block;width:35px;height:7px;background:#dfe3e8;border-radius:4px;margin-bottom:12px}.preview-card span{display:block;width:45px;height:10px;background:#222631;border-radius:4px}.preview-lower{display:grid;grid-template-columns:1.3fr .7fr;gap:9px;margin-top:9px}.preview-panel{height:150px;border:1px solid #edf0f3;border-radius:9px;padding:12px}.preview-panel em{display:block;width:72px;height:6px;background:#dfe3e8;border-radius:4px;margin-bottom:22px}.preview-chart{height:78px;position:relative;border-bottom:1px solid #edf0f3}.preview-chart:after{content:"";position:absolute;left:0;right:0;bottom:15px;height:46px;border-top:2px solid #5548c9;transform:skewY(-8deg)}.preview-lines{display:grid;gap:10px}.preview-lines span{height:8px;background:#e3e6eb;border-radius:4px}
        .nexora-footer{min-height:48px;display:flex;align-items:center;justify-content:flex-end;padding:0 clamp(22px,6vw,88px);color:#7a818d;font-size:11px;font-weight:500}
        @media(max-width:900px){.nexora-main{grid-template-columns:1fr;gap:38px;padding:52px 28px 38px;text-align:center}.nexora-copy{margin:0 auto}.nexora-description{margin:20px auto 26px}.nexora-preview{justify-self:center;width:min(100%,520px)}.nexora-footer{min-height:42px}}
        @media(max-width:560px){.nexora-nav{min-height:62px;padding:0 18px}.nexora-brand{font-size:18px}.nexora-mark{width:31px;height:31px}.nexora-signin{font-size:13px}.nexora-main{padding:48px 20px 34px;min-height:calc(100svh - 104px);align-content:start}.nexora-title{font-size:clamp(38px,12vw,50px);line-height:1.05}.nexora-description{font-size:15px;line-height:1.55;margin:18px auto 25px;max-width:330px}.nexora-button{width:100%;max-width:300px;padding:14px 18px}.nexora-preview{display:none}.nexora-footer{justify-content:center;padding:8px 18px;font-size:10px}}
      `}</style>
      <nav className="nexora-nav"><Link to="/" className="nexora-brand" aria-label="Nexora home"><span className="nexora-mark">N</span>Nexora</Link><Link to="/login" className="nexora-signin">Sign in</Link></nav>
      <section className="nexora-main"><div className="nexora-copy"><h1 className="nexora-title">Move work forward,<br />together<span>.</span></h1><p className="nexora-description">Projects, people, and progress in one place.</p><Link to="/register" className="nexora-button">Create account <ArrowRight size={16} aria-hidden="true" /></Link></div><div className="nexora-preview" aria-label="Nexora workspace preview"><div className="preview-bar"><i/><i/><i/></div><div className="preview-body"><aside className="preview-side"><strong>Nexora</strong><div className="preview-nav active"/><div className="preview-nav"/><div className="preview-nav"/><div className="preview-nav"/><div className="preview-nav"/></aside><div className="preview-content"><div className="preview-heading"/><div className="preview-cards"><div className="preview-card"><b/><span/></div><div className="preview-card"><b/><span/></div><div className="preview-card"><b/><span/></div></div><div className="preview-lower"><div className="preview-panel"><em/><div className="preview-chart"/></div><div className="preview-panel"><em/><div className="preview-lines"><span/><span/><span/><span/></div></div></div></div></div></div></section>
      <footer className="nexora-footer">© 2026 Nexora</footer>
    </main>
  );
}
