import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, Circle, Users } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import api from "../api";

type Project = { id:number; name:string; description:string; status:string };
type Task = { id:number; title:string; status:string; priority:string; projectId:number; projectName:string; dueDate?:string|null; assignee?:{id:number;name:string;email:string;role:string}|null };
type Member = { id:number; name:string; email:string; role:string };
const statuses = ["Todo","In Progress","Review","Done"];

function formatDueDate(value?: string|null) { if (!value) return "No due date"; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : d.toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"}); }

export default function ProjectDetails(){
  const { id } = useParams();
  const [project,setProject]=useState<Project|null>(null); const [tasks,setTasks]=useState<Task[]>([]); const [members,setMembers]=useState<Member[]>([]); const [error,setError]=useState("");
  const load=async()=>{try{const [p,t,m]=await Promise.all([api.get("/projects"),api.get("/tasks"),api.get("/team")]);const found=(p.data.projects||[]).find((x:Project)=>String(x.id)===String(id));setProject(found||null);setTasks((t.data.tasks||[]).filter((x:Task)=>String(x.projectId)===String(id)));setMembers(m.data.members||[]);}catch(err:any){setError(err.response?.data?.message||"Could not load project details.");}};
  useEffect(()=>{load();},[id]);
  const counts=useMemo(()=>statuses.map(s=>({s,n:tasks.filter(t=>t.status===s).length})),[tasks]);
  const progress=tasks.length ? Math.round((counts.find(x=>x.s==="Done")?.n||0)/tasks.length*100) : 0;
  if(!project) return <div className="workspace-page"><Link className="back-link" to="/projects"><ArrowLeft size={15}/> Back to projects</Link><div className="panel empty-state large">{error||"Project not found."}</div></div>;
  return <div className="workspace-page project-details-page">
    <Link className="back-link" to="/projects"><ArrowLeft size={15}/> Back to projects</Link>
    {error&&<div className="form-error page-alert">{error}</div>}
    <div className="project-hero panel"><div><p className="eyebrow">Project</p><h2>{project.name}</h2><p>{project.description||"No description yet."}</p></div><div className="project-progress"><strong>{progress}%</strong><span>Progress · {counts.find(x=>x.s==="Done")?.n||0} of {tasks.length} tasks completed</span><div className="progress"><div style={{width:`${progress}%`}}/></div></div></div>
    <div className="stats-grid project-stats"><div className="stat-card panel"><span>Tasks</span><strong>{tasks.length}</strong></div><div className="stat-card panel"><span>Completed</span><strong>{counts.find(x=>x.s==="Done")?.n||0}</strong></div><div className="stat-card panel"><span>In progress</span><strong>{counts.find(x=>x.s==="In Progress")?.n||0}</strong></div><div className="stat-card panel"><span>Workspace team</span><strong>{members.length}</strong></div></div>
    <div className="details-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Execution</p><h3>Project tasks</h3></div><span>{tasks.length} total</span></div><div className="project-task-list">{tasks.map(task=><div className="project-task" key={task.id}><div className="task-main"><span className="task-icon">{task.status==="Done"?<CheckCircle2 size={16}/>:task.status==="In Progress"?<Clock3 size={16}/>:<Circle size={16}/>}</span><div><strong>{task.title}</strong><span>{task.assignee?`Assigned to ${task.assignee.name}`:"Unassigned"}</span><span className="task-due"><CalendarDays size={12}/> Due: {formatDueDate(task.dueDate)}</span></div></div><div className="task-right"><span className={`status-pill ${task.status.toLowerCase().replaceAll(" ","-")}`}>{task.status}</span><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span></div></div>)}{!tasks.length&&<div className="empty-state">No tasks have been added to this project yet.</div>}</div></section>
      <aside className="panel"><div className="section-heading"><div><p className="eyebrow">People</p><h3>Workspace team</h3></div><Users size={17}/></div><div className="member-list">{members.map(m=><div className="member-row" key={m.id}><div className="avatar">{m.name?.slice(0,2).toUpperCase()}</div><div><strong>{m.name}</strong><span>{m.email}</span></div><em>{m.role}</em></div>)}{!members.length&&<div className="empty-state">No team members yet.</div>}</div></aside></div>
    <div className="panel project-info"><div><CalendarDays size={17}/><span>Project status</span><strong>{project.status}</strong></div><div><Users size={17}/><span>Workspace team</span><strong>{members.length} members</strong></div></div>
    <style>{`.back-link{display:inline-flex;align-items:center;gap:6px;color:#4f46a5;text-decoration:none;font-size:13px;font-weight:700;margin-bottom:16px}.project-hero{display:flex;justify-content:space-between;gap:30px;align-items:center}.project-hero h2{margin:4px 0 8px}.project-hero p{margin:0;color:#656c78;line-height:1.55}.project-progress{width:270px;flex-shrink:0}.project-progress strong{display:block;font-size:30px;color:#171a21}.project-progress span{display:block;color:#737985;font-size:12px;margin-bottom:9px}.project-stats{margin-top:14px}.details-grid{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(280px,.6fr);gap:14px;margin-top:14px}.section-heading{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-bottom:15px}.section-heading h3{margin:3px 0 0}.section-heading>span{font-size:12px;color:#737985}.project-task-list,.member-list{display:grid;gap:8px}.project-task{display:flex;align-items:center;justify-content:space-between;gap:12px;border:1px solid #e6e8ec;border-radius:9px;padding:12px}.task-main{display:flex;align-items:center;gap:10px;min-width:0}.task-icon{color:#5548c9;display:flex}.task-main strong,.task-main span{display:block}.task-main strong{color:#252936;font-size:14px}.task-main div span{color:#777e89;font-size:12px;margin-top:3px}.task-due{display:flex!important;align-items:center;gap:4px;color:#555c68!important}.task-right{display:flex;gap:7px;align-items:center;flex-wrap:wrap;justify-content:flex-end}.status-pill{font-size:11px;padding:5px 7px;border-radius:999px;background:#f0f1f4;color:#4a505b}.status-pill.done{background:#e9f7ef;color:#267044}.status-pill.in-progress{background:#eeecff;color:#5146a5}.status-pill.review{background:#fff4df;color:#8a5b12}.member-row{display:flex;align-items:center;gap:9px;border-bottom:1px solid #edf0f3;padding:9px 0}.member-row:last-child{border-bottom:0}.member-row .avatar{flex:0 0 34px;width:34px;height:34px}.member-row div:nth-child(2){min-width:0;flex:1}.member-row strong,.member-row span{display:block}.member-row strong{font-size:13px;color:#252936}.member-row span{font-size:11px;color:#777e89;overflow:hidden;text-overflow:ellipsis}.member-row em{font-style:normal;font-size:10px;color:#5548c9;font-weight:700}.project-info{display:flex;gap:30px;margin-top:14px}.project-info div{display:flex;align-items:center;gap:8px}.project-info span{color:#737985;font-size:12px}.project-info strong{color:#252936;font-size:13px}@media(max-width:800px){.project-hero{flex-direction:column;align-items:flex-start}.project-progress{width:100%}.details-grid{grid-template-columns:1fr}.project-info{flex-direction:column;gap:12px}}@media(max-width:520px){.project-task{align-items:flex-start;flex-direction:column}.task-right{justify-content:flex-start}.project-hero{padding:18px}.project-info{padding:14px}.project-stats{grid-template-columns:repeat(2,minmax(0,1fr))}}`}</style>
  </div>;
}
