import { useEffect, useMemo, useState } from "react";
import { CalendarDays, FolderKanban, Plus, Search, Trash2, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import api from "../api";

type Project = { id:number; name:string; description:string; status:string; progress:number; memberCount?:number; createdAt?:string };
type StoredUser = { role?:string };
function currentRole(){ try{return (JSON.parse(localStorage.getItem("nexora_user")||"{}") as StoredUser).role||"Member";}catch{return "Member";} }

export default function Projects(){
  const navigate=useNavigate(); const [projects,setProjects]=useState<Project[]>([]); const [form,setForm]=useState({name:"",description:""}); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [search,setSearch]=useState("");
  const role=currentRole(); const canManageProjects=role==="Admin"||role==="Manager";
  const load=()=>api.get("/projects").then(({data})=>setProjects(data.projects||[])).catch((err)=>setError(err.response?.data?.message||"Could not load projects."));
  useEffect(()=>{load();},[]);
  async function createProject(){if(!form.name.trim()||!canManageProjects)return;setLoading(true);setError("");try{await api.post("/projects",form);setForm({name:"",description:""});await load();}catch(err:any){setError(err.response?.data?.message||"Could not create project.");}finally{setLoading(false);}}
  async function removeProject(id:number){if(!canManageProjects)return;try{await api.delete(`/projects/${id}`);await load();}catch(err:any){setError(err.response?.data?.message||"Could not delete project.");}}
  const visible=useMemo(()=>projects.filter(p=>!search.trim()||p.name.toLowerCase().includes(search.toLowerCase())||p.description?.toLowerCase().includes(search.toLowerCase())),[projects,search]);
  return <div className="workspace-page">
    <div className="page-heading"><div><p className="eyebrow">Workspace</p><h2>Projects</h2><p>Every project is a shared place for its people, tasks, deadlines and progress.</p></div>{canManageProjects&&<button className="primary-button" onClick={()=>document.getElementById("project-name")?.focus()}><Plus size={15}/> New project</button>}</div>
    {error&&<div className="form-error page-alert" role="alert">{error}</div>}
    {canManageProjects?<div className="panel create-panel"><div><p className="eyebrow">Create</p><h3>Start a new project</h3><p>Create the project first; then open it to see tasks and people working on it.</p></div><div className="form-row"><input id="project-name" className="workspace-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Project name"/><input className="workspace-input" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Short description"/><button className="primary-button" onClick={createProject} disabled={loading}>{loading?"Creating...":<><Plus size={15}/> Create</>}</button></div></div>:<div className="panel permission-note"><strong>View projects</strong><span>Your {role.toLowerCase()} access lets you work with projects you are allowed to see. Managers and admins create or remove projects.</span></div>}
    <div className="panel project-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects"/><span>{visible.length} projects</span></div>
    <div className="card-grid">{visible.map(p=><article className="panel project-card" key={p.id} onClick={()=>navigate(`/projects/${p.id}`)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")navigate(`/projects/${p.id}`)}}><div className="card-icon"><FolderKanban size={18}/></div><div className="card-title"><h3>{p.name}</h3>{canManageProjects&&<button className="danger-button" onClick={e=>{e.stopPropagation();removeProject(p.id)}} aria-label={`Delete ${p.name}`}><Trash2 size={14}/></button>}</div><p>{p.description||"No description yet. Open the project to add context, tasks and people."}</p><div className="project-meta"><span>{p.status}</span><strong>{p.progress}% complete</strong></div><div className="progress"><div style={{width:`${Math.max(0,Math.min(100,p.progress||0))}%`}}/></div><div className="project-meta" style={{marginTop:13}}><span><Users size={12} style={{verticalAlign:"-2px"}}/> {p.memberCount||0} project members</span><span><CalendarDays size={12} style={{verticalAlign:"-2px"}}/> Created {p.createdAt?new Date(p.createdAt).toLocaleDateString(undefined,{day:"numeric",month:"short"}):"recently"}</span></div><small className="project-open-hint">Open project → tasks · people · progress</small></article>)}</div>
    {!visible.length&&<div className="panel empty-state large">{search?"No projects match your search.":canManageProjects?"No projects yet. Create your first project above.":"No projects are available to you yet."}</div>}
    <style>{`.project-search{display:flex;align-items:center;gap:8px;margin:14px 0}.project-search input{border:0;outline:0;flex:1;padding:10px 0;background:transparent;color:#252936}.project-search span{font-size:12px;color:#737985}.project-open-hint{display:block;margin-top:12px;color:#5548c9;font-weight:700}.project-card{cursor:pointer}.project-card:focus-visible{outline:2px solid #5548c9;outline-offset:2px}@media(max-width:600px){.project-search{margin-bottom:12px}.project-search span{display:none}}`}</style>
  </div>;
}
